### ISSUE TITLE
Sharing buttons

### ISSUE THREAD

**Issue by puneethkanna** [devskrate/prod#11]
![Screenshot from 2020-06-29 08-40-33](https://user-images.githubusercontent.com/40000406/85969070-3f114580-b9e4-11ea-9d77-d35f6b2968a8.png)

**Comment by puneethkanna** [comment]
The share buttons at the top of the page at feature image is more comfortable for user, rather than at the bottom.
What to you say @SriSatyaLokesh and @VasaviLagishetty and @nikhilpyreddy

**Comment by SriSatyaLokesh** [comment]
I will take care of this

**Comment by SriSatyaLokesh** [comment]
![image](https://user-images.githubusercontent.com/43106076/86260214-9b3dba80-bbda-11ea-8c21-00013f37d372.png)
![image](https://user-images.githubusercontent.com/43106076/86260219-9d077e00-bbda-11ea-8f9d-24c7ab715887.png)


closing this issue
