### ISSUE TITLE
Dark Mode text fixes

### ISSUE THREAD

**Issue by puneethkanna** [devskrate/prod#15]
![Screenshot from 2020-07-01 19-13-33](https://user-images.githubusercontent.com/40000406/86251058-02ee0880-bbcf-11ea-99bc-720797a9ce2d.png)

**Comment by puneethkanna** [comment]
Dark mode is working fin, but in the side view The subtitle or description is in black. This need to be changed to white

**Comment by SriSatyaLokesh** [comment]
Why image is in negative shade?

**Comment by puneethkanna** [comment]
> Why image is in negative shade?

I used the firefox screenshot. Now I have updated it.

**Comment by SriSatyaLokesh** [comment]
everything is good right?

**Comment by puneethkanna** [comment]
![image](https://user-images.githubusercontent.com/40000406/86251262-42b4f000-bbcf-11ea-932c-2af8a6c74163.png)

**Comment by SriSatyaLokesh** [comment]
thats image issue not title.

**Comment by puneethkanna** [comment]
![Screenshot from 2020-07-01 19-16-24](https://user-images.githubusercontent.com/40000406/86251341-5fe9be80-bbcf-11ea-8648-3ceacca7b113.png)

**Comment by SriSatyaLokesh** [comment]
Yes puneeth thats's alt text for image

**Comment by puneethkanna** [comment]
Oh, sorry. It's a mistake.

**Comment by puneethkanna** [comment]
I just seen the text is not changing color, but forgot about image

**Comment by SriSatyaLokesh** [comment]
![image](https://user-images.githubusercontent.com/43106076/86251527-9a535b80-bbcf-11ea-8572-502731aa9bc3.png)

![image](https://user-images.githubusercontent.com/43106076/86251628-be16a180-bbcf-11ea-83af-deaf3b5d7e5b.png)



@VasaviLagishetty  take care of blockquote also in dark mode along with h1..h6, p tag

**Comment by VasaviLagishetty** [comment]
I will update it

**Comment by puneethkanna** [comment]
![Screenshot from 2020-07-01 22-08-37](https://user-images.githubusercontent.com/40000406/86269554-8ca9d000-bbe7-11ea-9f1b-fe533f506b2a.png)

**Comment by puneethkanna** [comment]
I think we need to change the text to white rather than the background to white.

**Comment by puneethkanna** [comment]
We can also serach for dark 404 pages, it will be more usefull
