### ISSUE TITLE
Dark mode toggle issue

### ISSUE THREAD

**Issue by SriSatyaLokesh** [devskrate/prod#16]
![image](https://user-images.githubusercontent.com/43106076/86251840-05049700-bbd0-11ea-9735-3791f0c56d6e.png)
![image](https://user-images.githubusercontent.com/43106076/86251844-0766f100-bbd0-11ea-84d0-beea5b8b75ce.png)

we should see moon in light mode and sun in dark mode

**Comment by SriSatyaLokesh** [comment]
Also give a light white border dto toggle button so that people can understand

**Comment by puneethkanna** [comment]
![Screenshot from 2020-07-01 22-43-50](https://user-images.githubusercontent.com/40000406/86272598-72bebc00-bbec-11ea-8ea0-5787b3a21927.png)
![Screenshot from 2020-07-01 22-43-52](https://user-images.githubusercontent.com/40000406/86272616-78b49d00-bbec-11ea-8caa-e5601c27c461.png)

**Comment by puneethkanna** [comment]
The toggle is reversing its nature when reloaded or just done some heavy testing.

**Comment by puneethkanna** [comment]
I don't know if this persistes for others. If no, we can close the issue

**Comment by SriSatyaLokesh** [comment]
we know this. tried hard. we want use case to be there. we are fine with this.
