### ISSUE TITLE
Link symbol missing in darkmode

### ISSUE THREAD

**Issue by SriSatyaLokesh** [devskrate/prod#20]
![image](https://user-images.githubusercontent.com/43106076/87296914-2f861680-c525-11ea-806f-5d268ca135ed.png)

![image](https://user-images.githubusercontent.com/43106076/87296920-31e87080-c525-11ea-986e-8807ca3bd0a9.png)

If you can see there's a black link in light mode which comes in hovering a title. we need that in darkmode too.

**Comment by VasaviLagishetty** [comment]
That is an image how do I change it in dark mode

**Comment by VasaviLagishetty** [comment]
![image](https://user-images.githubusercontent.com/47534164/87574441-fe0b7780-c6eb-11ea-9047-45746191d667.png)
![image](https://user-images.githubusercontent.com/47534164/87574468-0663b280-c6ec-11ea-9e77-5d411ed71185.png)
