### ISSUE TITLE
Author image and share icons are over the recommended post

### ISSUE THREAD

**Issue by nikhilpyreddy** [devskrate/prod#22]
![image](https://user-images.githubusercontent.com/39935451/87300696-ed140800-c52b-11ea-86e2-ff6ad24d00a1.png)
![image](https://user-images.githubusercontent.com/39935451/87300739-06b54f80-c52c-11ea-8b4e-a3da9eb824a0.png)

**Comment by SriSatyaLokesh** [comment]
decrease z index of this images in CSS, This will get fixed

**Comment by VasaviLagishetty** [comment]
Done
[image](https://user-images.githubusercontent.com/47534164/87306070-1be2ac00-c535-11ea-8003-fb9e59ae9937.png)
![image](https://user-images.githubusercontent.com/47534164/87306104-28ff9b00-c535-11ea-9563-3c078bec1c92.png)
