### ISSUE TITLE
Table headigposition

### ISSUE THREAD

**Issue by SriSatyaLokesh** [devskrate/prod#23]
![image](https://user-images.githubusercontent.com/43106076/87388641-d4a2fc80-c5c2-11ea-8ebc-132360cbd0a2.png)
headings should be left algined

**Comment by VasaviLagishetty** [comment]
done
![image](https://user-images.githubusercontent.com/47534164/87419575-5ad63780-c5f1-11ea-9a54-2c6fb11c6814.png)
