### ISSUE TITLE
Size of Headings

### ISSUE THREAD

**Issue by puneethkanna** [devskrate/prod#9]

**Comment by puneethkanna** [comment]
Need to decrease the size of the heading in mobile view.

**Comment by puneethkanna** [comment]
![Screenshot from 2020-06-29 08-33-07](https://user-images.githubusercontent.com/40000406/85968630-38360300-b9e3-11ea-9672-8d41dfe78a8c.png)

**Comment by SriSatyaLokesh** [comment]
@puneethkanna  isn't this fixed?

**Comment by puneethkanna** [comment]
Yes, the size is decreased.
